classes/Orbit_class.f90
Currently the getSolarElongation_Orb function tries to set values for 6 elements of a 3-element array. This is a bug, and breaks compilation with the Intel compiler. This commit fixes the issue, and thus compilation with ifort works again.
=> Fix bug in Orbit causing compilation with ifort to fail

python/oorb_2b.conf, python/oorb_nb.conf, python/pyoorb.f90, python/test.py, python/test_2.py
Via the python interface (pyoorb.f90): 
There is an option for orbit propagation with either 2-body or n-body integration; however, there was no option for 2-body integration if the user wanted to do ephemeris generation.  This PR adds that option. There is also an update in test.py and addition of test_2.py to test the 2-body ephemeris generation. test_2.py also compares python vs. command line calculation of ephemerides.
=> Add 2body ephemeris generation option to pyoorb.f90

main/oorb.f90
I tested this and can confirm that this fixes the issue.
=> Correctly nullify storb in lsl (fixes bug #39)

README.md, main/oorb.f90
This smaller PR adds support for loading multiple observation files, that do not necessarily have to be of the same file type, simultaneously. To use, add each desired file to --obs-in separated by commas, eg. --obs-in=file1,file2,file3 .
Using a single observation file will work exactly as before. 
This currently doesn't support multiple orbit files but I can probably implement that as well if you wish.
=> Support for inputting multiple obs files

modules/integrators.f90
I found a memory leak when BC430 ephemerides are being used. This quick commit fixes it.
=> Fix memory leak with BC430

classes/Orbit_class.f90
For whatever reason, in two cases NULLIFY fails to free up memory taken by two pointers in one of the getEphemeris routines, resulting in nasty memory leaks. Using DEALLOCATE instead fixes this problem for me.
=> Deallocate some pointers in getEphemeris rather than nullify

classes/Observations_class.f90
Currently oorb reads asteroid designations in DR2 as integers and converts them to strings. However, the MPC uses 5 character designations for asteroids, e.g. asteroid 455 = 00455.
This causes oorb to consider asteroids 455 and 00455 different objects, which I don't want. So, I'm changing the designations in gdr2 files from 455 to 00455.
This isn't enough when the designation is read as an integer because as integers, 00445 = 445.
This small PR removes that particular problem and slightly simplifies the code besides.
=> Read gdr2 designations as strings rather than integers

classes/Orbit_class.f90
Memory leak seems to be fixed by adding RETURN and deallocating one vector. This subroutine (getTopocentricSCoord in Orbit class) is currently not used by any other routine, so this should not break anything else.
=> Fixing memory leak in orbit linking

README.md, python/README.rst, python/pyoorb.f90
this pr comes with the following changes:
* pyoorb: fix to #70: brightness predictions are now always in the HG system, a useless write statement was removed
* conda installer guidelines added to oorb/README
* conda installer guidelines added to oorb/pyoorb/README; docs updated
=> pyoorb fixes and docs update

build/Makefile
The "clever" idea to embed a comment by hiding it behind the `:` backfired, as that erased all the environmental variable manipulation happening in the complicated line above it. Bad Mario :)...
=> Fix Linux conda gfortran build breakage accidentally introduced by #80

.gitignore, Makefile, README.md, azure-pipelines.yml, azure-tpl-jobs.yml, build/Makefile, codecov.yml, configure, data/JPL_ephemeris/Makefile
Hi @mgranvik, @Siltala et al.:
This PR adds the configuration files needed to automatically run builds and tests on [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) continuous integration service, and the [codecov.io](http://codecov.io) code coverage visualization service.
Once hooked up, Azure's CI will automatically builds oorb on a matrix of operating systems and Python versions every time a new commit is pushed onto master, and also whenever a pull request is made (so you'll know if the PR breaks existing code).
Eight builds are made in total (macOS w. conda w. py27, 36, 37; Ubuntu w. conda w. py27, 36, 37; and Ubuntu with system Python 2.7 and 3.5) and it runs tests on all of them. The builds are done in parallel and typically take 3-4 minutes (for all …
=> Hooking up OpenOrb to CI

modules/integrators.f90
Currently the Bulirsch-Stoer integrator fails if n-body integration is being used with all perturbers disabled (I suppose I'm the only one who ever does that?)
This short PR fixes the issue.
=> Fix integrator failure when no perturbers are set

classes/File_class.f90, classes/Observations_class.f90
Making available normal-point treatment of Gaia short term data. Each Gaia transit is collapsed into a normal point upon reading. The data is identified with the "gaianp" suffix. 
This pull request includes the following changes:
File_class.f90 : auxiliary function matchCharNrLines
Observations_class.f90: option for files with the "gaianp" suffix, and auxiliary subroutines: collapseTransit, computeFinalT, collapseGaiaPos, CollapseGaiaVel
Tested to work with systematic ranging. Failed with random-walk ranging, but this seems to be a separate issue.
=> Adding normal-point treatment for Gaia short-term data.

build-tools/make-fortran-deps.sh, build/Makefile
=> bugfix: make depends broken if $FC wasn't externally set

doc/OpenOrb_Tutorial.tex
This PR updates the openorb tutorial to reflect the fact that we now use the de430 ephemeris by default, and also restores the previously used citation style.
The .tex documentation does remain very outdated (last update was 7 years ago!)
=> Documentation update

data/getBC430
New attempt to fix #100 .
This updates getBC430 such that it downloads the BC430 data files from Zenodo, unpacks the archive (this assumes that the user has tar in stalled, but I would be surprised if someone -didn't- have it installed) and finally removes the tar.gz archive, leaving only the relevant data files in the folder.
=> Update getBC430 script

modules/planetary_data.f90
This PR should fix #97. 
It turns out that with non-consecutive perturbers enabled, the masses (in asteroids_masses.txt) were read from incorrect lines.
I tested that the fix works by computing a lsl orbit for an asteroid with a close encounter with Vesta by enabling Vesta's perturbations but not those of Ceres and Pallas, which works well with this patch but not without.
=> Fix reading BC430 masses with non-consecutive perturbers enabled

classes/Observations_class.f90
As discussed in private email, it seems there's currently an inaccuracy of ~10 ms inside oorb in observation epochs when using Gaia DR2 data.
It turns out that the problem has something to do with timescale conversions; when using the UTC observation epochs from the .gdr2 data files directly, the problem seems to disappear. This commit does just that and thus works around the problem.
=> Use the UTC epoch instead of TCB when reading Gaia data

classes/StochasticOrbit_class.f90
Just a simple commit to raise an error if getID is called on a storb object that doesn't actually have an ID instead of returning a blank string.
=> getID_SO: check if the object's ID is actually initialized

main/oorb.f90
Currently oorb sets an output filename for things e.g. lsl's .ls file based on the filename of the input observations. This changes that behavior to set the output name based on --orb-out instead. If it is not given, we fall back to the old behavior.
The advantage here is that this is a LOT more convenient during development and also certain use cases; under the current scheme if you calculate several lsl orbits based on the same data files the residuals for each of these orbits all end up in the same file and it gets very difficult to figure out which is which. With this commit that is no longer an issue.
=> Set output filenames based on --orb-out if given

README.md, build/Makefile, configure, modules/linal.f90
I think that this is now ready for merging. The new code produces very similar (but not always 100% equivalent) results to the old code and, based on my limited testing, seems mathematically correct.
This PR replaces oorb's LU and Cholesky factorization and matrix inversion based on both with functions from LAPACK. 
As far as the rest of the code outside linal.f90 is concerned, nothing has changed (the 'old' functions are there and are used in the same way but, inside linal.f90, the internal behavior of the functions has.)
There may be room for using LAPACK elsewhere in the code, but that can always be done later (?)
=> First steps for replacing oorb's linear algebra functions with those of LAPACK

.github/workflows/CI_tests.yml
This works around #112 and doesnt affect any functionality outside the CI.
=> Install CI numpy with pip rather than homebrew

make.config
This adjusts the default optimization flags for gfortran. -O3 is switched to -O2 (which for oorb, and some other programs, appears to be slightly faster?), link-time optimizations are added (-flto) among with loop unrolling and 2 optimizations which ifort apparently uses with O3 already (and thus oorb) 
Based on my testing, on my system this gives a ~11% speedup for running n-body lsl computations and at least in the CI none of the results change. Compilation time however almost doubles but I at least think it's worth it. Further testing is welcome!
For my test I ran lsl four times with both these flags and the old optimizations and compared the mean run times of each (174 seconds with the new flags, 196 with the old)
I also note that I've been using these optimization flags on my end for …
=> Add more gfortran optimizations

classes/StochasticOrbit_class.f90, main/oorb.f90
This PR removes an unnecessary (and wrong) if block from the MCMC residual printing task and also fixes a minor memory leak that slipped into my residual printing function.
=> Mass estimation code updates

classes/PhysicalParameters_class.f90
A quick fix for a MCMC bug where the number of accepted proposals was not printed out for the last accepted one (which is always 1)
Not really interesting in a scientific sense but it does solve problems with some plotting scripts of mine (in the past I've just removed the single troublesome line manually from the result files..)
=> massEstimation_mcmc: minor output fix

classes/PhysicalParameters_class.f90, main/oorb.f90
This PR cleans up the mass_estimation_march code a little bit and adds a new (optional) command line option to specify the resolution of the run (that is to say, the number of masses that are tested). I will document it on the wiki once the PR is merged.
No changes outside the marching algorithm.
=> mass_estimation_march: code cleanups and option to specify resolution

build-tools/compute-version.sh
While getting ready for a new official release (woo!) I noticed that there appears to be a bug in compute-version.sh where, according to comments, the intended behavior is
`If the current commit has an annotated tag attached to it, the version is simply the tag with the leading 'v' removed.`
However, this doesn't currently occur in practise as the tags are not checked at all. This quick PR seems to fix that (tagging -heh-  @mjuric - does this make sense?)
I suppose that this has simply never come up before because we've never actually had any tags before.
=> Correctly include tags in compute-version.sh

classes/PhysicalParameters_class.f90, classes/StochasticOrbit_class.f90
Fixes an annoying problem in the MCMC mass estimation code where the proposal matrices were sometimes not properly printed out until the end of the run (making resuming old runs troublesome) by closing the file after each write.
Also properly nullifies all files at the end of the run, just in case.
Partway through working on this I was told that today is a national holiday in Finland.. :)
=> mass_estimation_mcmc fixes

classes/StochasticOrbit_class.f90, modules/utilities.f90
This partially fixes #87 by correctly initializing a rms vector as 6-dimensional.
As noted in my comment on the relevant issue, the crash only occurs with debug builds because the rms values are not actually used anywhere (as far as I can tell) so the compiler is presumably optimizing the line out and thus avoiding the crash. As such, it might make more sense to just remove the rms computation entirely but, for now, I chose to keep it there just in case it's there for a reason..
With this commit, Grigori's test case still does crash for me with a debug build later - in makeResidualStamps, specifically, with the relevant error being `(io / makeResidualStamps) TRACE BACK (80)` which points to the culprit being the toString function (which is called with the float value …
=> Random walk ranging: correct the dimensions of the rms vector

.github/workflows/CI_tests.yml
Turns out a change in homebrew's installation syntax broke the Mac CI script. Here's a quick fix.
Doesn't affect anything beyond the CI
=> Mac CI: Update gfortran install command

classes/Base_class.f90, main/oorb.f90, modules/planetary_data.f90, modules/utilities.f90
This PR adds a possible solution to #118 . It uses the resolveDirectory to check PREFIX/share/oorb for the gnuplot scripts -if- OORB_GNUPLOT_SCRIPTS_DIR is not defined.
Similarly, resolveDirectory has been copied to planetary_data.f90 (because Base_class.f90 is not included there, and presumably you don't want to do so) and is used there to check the same directory for the BC430 files if OORB_DATA is not defined. It adds prefix.h as an include because the PREFIX is stored there.
Let me know if you're not happy with this and I'll see if I can adjust things.
=> Datafile IO updates

configure, data/JPL_ephemeris/Makefile
The additions to the configure file add the flags needed to let someone compile using gfortran and lapack provided by conda otherwise these versions - particularly the lapack library - aren't found correctly. 
The additions to the data/JPL_ephemeris/Makefile are similar, and use the same options set in the configure step.
To use these options, someone would then build using
'./configure conda opt --with-pyoorb' (for example). 
If 'gfortran' is used for the configure step, the conda versions will not be used. 
I note that I had some issue with lapack library version finding when trying to install without conda and using the homebred-installed gfortran .. it seemed like the home-brew and system lapack were having some issues. Using 'conda', I was able to install the ephemeris files …
=> Add additional options to compile with 'conda' provided gfortran

configure, main/ephemeris_linking.f90, main/orbit_linking.f90, make.config
This PR adds support for compiling oorb with the "new", shiny open-source `flang` compiler which is part of the LLVM project.
LLVM 12+ is required - when I tried with 11 some time ago, oorb did not build, but as of version 12 it does.
As with other compilers. to use flang you just call `configure` with e.g. `./configure flang opt` and it will work.
Based on my (limited) testing, the performance delta between gfortran 11.1.0 and flang 12 is less than 1% (in gfortran's favor) so they are pretty much equivalent in that sense.
One change to the code was necessary to get things to work - `getpid` and `system` needed to be explicitly declared in orbit_linking and ephemeris_linking. It should not break anything - at least gfortran seems to still work fine.
This is documented in e.g. …
=> Implement support for the flang compiler

classes/Observations_class.f90, classes/PhysicalParameters_class.f90, classes/StochasticOrbit_class.f90, main/io.f90, main/oorb.conf, main/oorb.f90
Contains various fixes and tweaks mainly regarding resuming previous MCMC mass estimation runs and computing the acceptance criterion a_r (the algorithm itself is unchanged)
Also a commit is added to no longer force the RAM adaptation scheme when resuming a previous run - other schemes crashed that case before, but no longer (of course it can still used if the user so chooses, and it's probably a good idea to do so).
Routines for masking and unmasking Gaia observations are included, to be used with MCMC mass estimation to avoid local minima.
Relativistic correction based on F. Mignard's code for Gaia DR2 data is implemented.
MCMC mass estimation options are added in oorb.conf.
Then there are some other random odds and ends.
=> MCMC fixes and updates

build-tools/get-python-extension-suffix.sh
python3-config is a script which is included in `python3-dev` when you install on Ubuntu, but it's not at all standard or part of the Python standard library. That script just runs `sysconfig.get_config_var("EXT_SUFFIX")`.
But since it's a script installed by the OS package manager, it's not controllable with virtualenvironments or with conda. So on systems with multiple Python versions (eg with environments) it will give the wrong answer, which breaks the build. This fixes that.
=> Use Python to look up extension suffix, not python3-config which is nonstandard

.github/workflows/CI_tests.yml, .github/workflows/python_wheels.yml, .gitignore, pyproject.toml, python/COPYING, python/setup.py, setup.py
This is a first crack at the basics for #135. It adds a `python/setup.py` file which hooks into setuptools to allow building a binary distributable wheel.
It relies on the existing Makefile to do all the heavy lifting; it just copies the resulting `pyoorb.[...].so` and packages it as a wheel.
Some obvious todos to accomplish #135:
- The `setup()` call should be filled out with more info: a project description, list of maintainers, and so on.
- This should be tested on OSX and other Python versions - I have only done it on Linux and with Python 3.8
- Need to also add infrastructure to build it in github actions, and upload releases to PyPI.
- I am a little bit worried about the wheel's portability. Running `auditwheel show` on it shows that it relies on shared libraries:
```
-> % …
```
=> Build Python Wheel from pyoorb

main/oorb.f90, modules/sort.f90
The ephemeris task was missing a call to nullify the `t` object which led to crashes when trying to generate ephemerides for multiple objects without covariance matrices. 
The one-liner here fixes that problem.
Also, a separate commit is added to increase the nstack parameter to fix #159
=> Misc fixes

configure
Support calling `./configure --with-compiler-options`, for example `./configure gfortran --with-compiler-options=-march=native`.  
This is useful to me because `-march=native` improves performance dramatically, at the cost of making the built binary only good for the architecture it was built on. In some informal experiments on an Intel Cascade Lake CPU, this makes propagations 30-40% faster.
=> Support setting additional compiler flags

.github/workflows/pypi_publish.yml
Add pushes of built wheels to PyPI. This is triggered by publish actions of github releases.
This hasn't been tested end-to-end, really, since it is written to be triggered only by publishing a github release. I _think_ that should communicate the right Git tag information through so that the version is set properly, but it's hard to be sure of that until we actually attempt a github release.
I would suggest verifying the workflow by publishing a prerelease version. The version string needs to comply with [PEP-440](https://peps.python.org/pep-0440/) so it could be something like `1.3.0a1` to indicate "alpha 1", and `1.3.0a2` if that doesn't work, and so on, incrementing the counter until it actually works; then it could be `1.3.0`.
Take care that the git tag must be prefixed by `v`, so …
=> Publish wheels to PyPI

.github/workflows/pypi_publish.yml
Python 3.12 was released on October 2, two days ago. This fixes #175.
=> Build and publish Python 3.12 wheels

classes/Observations_class.f90
As per PR title, this introduces initial support from the Gaia FPR. Only very limited testing has been done so far, but so far things seem to work. Note that the required suffix for FPR data is 'gfpr' for oorb to recognize it.
=> Initial support for the Gaia FPR
